In [ ]:
import pandas as pd
url = "https://raw.githubusercontent.com/rajendra0968jangid/Ds-Arya/main/student-data.json"
df = pd.read_json(url)

# by default ascending
df.sort_values("english")
 
# decending
df.sort_values("english",ascending=False)

#multiple sort
df.sort_values(by=['english'],ascending=[False])
 
# a to z
df['name'] = df['name'].str.lower()
df.sort_values("name")

       name  gender  physics  maths  english
10    Gowri  Female      100    100      100
1    rajesh    Male       96    100       95
13  Jenifer  Female       67     88       90
4      usha  Female       67     45       78
5     priya  Female       56     46       78
0      arun    Male       88     87       78
12  Murugan    Male       34     89       78
2   moorthy    Male       89     90       70
7   Kavitha  Female       78     71       67
6    Sundar    Male       12     67       67
8    Dinesh    Male       56     45       67
11      Ram    Male       78     55       47
3      raja    Male       30     25       40
9      Hema  Female       71     90       23

In [6]:
import pandas as pd
url = "https://raw.githubusercontent.com/rajendra0968jangid/Ds-Arya/main/student-data.json"
df = pd.read_json(url)

#add column total
df["total"] = df['physics'] + df['maths'] + df['english']

#add row
df.loc[14] = ["rajendra",'Male',50,80,80,210]
print(df)

#update column

#update row

#delete column
df.drop("total",axis=1)

#delete row
df.drop(14,axis=0)

#delete row and column
df.drop([6,7,8,9,10,11,12,13,14],inplace=True)


df['doj'] = ['2025-01-01','2025-02-02','2025-03-03','2025-04-04','2025-05-05','2025-06-06']
df

        name  gender  physics  maths  english  total
0       arun    Male       88     87       78    253
1     rajesh    Male       96    100       95    291
2    moorthy    Male       89     90       70    249
3       raja    Male       30     25       40     95
4       usha  Female       67     45       78    190
5      priya  Female       56     46       78    180
6     Sundar    Male       12     67       67    146
7    Kavitha  Female       78     71       67    216
8     Dinesh    Male       56     45       67    168
9       Hema  Female       71     90       23    184
10     Gowri  Female      100    100      100    300
11       Ram    Male       78     55       47    180
12   Murugan    Male       34     89       78    201
13   Jenifer  Female       67     88       90    245
14  rajendra    Male       50     80       80    210

      name  gender  physics  maths  english  total         doj
0     arun    Male       88     87       78    253  2025-01-01
1   rajesh    Male       96    100       95    291  2025-02-02
2  moorthy    Male       89     90       70    249  2025-03-03
3     raja    Male       30     25       40     95  2025-04-04
4     usha  Female       67     45       78    190  2025-05-05
5    priya  Female       56     46       78    180  2025-06-06

In [18]:
import pandas as pd
url = "https://raw.githubusercontent.com/rajendra0968jangid/Ds-Arya/main/file2.json"
df = pd.read_json(url)
print(df)
print("\n")

df['doj'] = ['2025-01-10','2025-02-10','2025-03-10','2025-04-10','2025-05-10']
df['doj'].dtype

#convert string to date
df['doj'] = pd.to_datetime(df['doj'])
df['doj'].dtype

#date operation
df['doj'].dt.year
df['doj'].dt.month
df['doj'].dt.day
df['doj'].dt.day_name()

#20 days
df['doj'] + pd.to_timedelta("20 days")
df['doj'] + pd.to_timedelta(20,unit='D')

       name  roll no  marks
0   dheeraj      123     10
1     kunal     1234     20
2  abhishek    12345     30
3   praveen    12356     40
4    anjali  1234567     50

0   2025-01-30
1   2025-03-02
2   2025-03-30
3   2025-04-30
4   2025-05-30
Name: doj, dtype: datetime64[us]